import type { Metadata } from 'next'
import { Fira_Sans } from 'next/font/google'
import './globals.css'

const firaSans = Fira_Sans({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600'] })

export const metadata: Metadata = {
  title: 'Portfólio - SidGabriel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${firaSans.className} bg-[#000000] w-[100vw] h-[100vh]`}>{children}</body>
    </html>
  )
}