import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/siteComponents/navbar'

const noto = Noto_Sans({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600'] })

export const metadata: Metadata = {
  title: 'Portfólio - SidGabriel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${noto.className} bg-[#000000] w-[100vw] h-[100vh] p-3`}>
        {children}
        <Navbar/>
      </body>
    </html>
  )
}